In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
arr=np.array([10,20,30,40])
print(arr)
print(type(arr))
print(np.__version__)

[10 20 30 40]
<class 'numpy.ndarray'>
1.26.4


In [ ]:
#Dimenstion in  Array

In [9]:
arr=np.array(10)
print(arr)
print(arr.ndim)
arr1=np.array([10,20,30,40])
print(arr1)
print(arr1.ndim)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

10
0
[10 20 30 40]
1
[[1 2 3]
 [4 5 6]]
2


In [15]:
arr4=np.array([1,2,3,4],ndmin=10)
print(arr4)
print("Number of dimensions::",arr4.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
Number of dimensions:: 10


In [19]:
#Access the array element
print(arr1)
print(arr1[0])
print(arr1[0:3])
print(arr1[-3:-1])
print(arr1[::2])
print(arr1[0]+arr1[1])

[10 20 30 40]
10
[10 20 30]
[20 30]
[10 30]
30


In [23]:
#Copy 
arr=np.array([10,20,30,40])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42 20 30 40]
[10 20 30 40]


In [25]:
print(arr.shape)

(4,)


In [27]:
#Reshaping from 1d and 2d array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [31]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [33]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#Stack Function
#Stacking is same as concatenation the only difference is that stacking is done along as new axis

In [39]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [45]:
#Stack along with rows
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
# arr=np.hstack((arr1,arr2))
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [47]:
#Stack along with rows
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [49]:
#Filtering Array
arr=np.array([41,42,43,44])
x=[True,False,True,True]
newarr=arr[x]
print(newarr)

[41 43 44]


In [63]:
#Generate the Random Number
from numpy import random
x=random.randint(100,size=(2,10))
x

array([[85, 51, 11, 52, 53, 22,  1, 63, 70, 47],
       [71,  6, 46,  6, 49,  5, 40, 81, 34, 48]])

In [101]:
#Choice methods allows you to generate a random values based on an array of values
from numpy import random
x=random.choice([10,20,30,40],size=(3,5))
print(x)

[[10 20 20 10 40]
 [40 40 20 40 40]
 [20 40 30 10 20]]


In [ ]:
#Shuffing arrays
#Shuffing means changing arragement of elements in-place  i.e)in the array

In [112]:
from numpy import random
import numpy as np
arr=np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

[1 2 3 4 5]


In [124]:
#Permutation methods return a re-arraged array and leave the original array unchanged
arr1=np.array([1,2,3,4,5])
print(random.permutation(arr1))

[1 3 5 4 2]


In [126]:
arr=np.arange(10,100)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [128]:
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [130]:
v=np.linspace(0,20,5)
print(v)

[ 0.  5. 10. 15. 20.]


In [132]:
x=[1,2,3]
a=np.asarray(x)
print(a)

[1 2 3]


In [134]:
arr=np.zeros(8)
arr3d=arr.reshape((2,2,2))

print(arr3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [136]:
arr=np.arange(20)
arr_slice=slice(1,10,2)
element=arr[6]
print(arr[arr_slice])

[1 3 5 7 9]
